### ISSUE TITLE
email valido

### ISSUE THREAD

**Issue by FalaiTio** [sysborg/autentiquev2#2]
Estou usando a api com symfony (5).
Qnd vou cirar os documentos (conforme o exemplo da pasta test) da erro no email (gmail)
diz que é inválido:

`NOTICE: PHP message: [critical] Uncaught PHP Exception Exception: "en-US: Variable email must be a valid email, please verify the entry and try again! | pt-BR: A variável email deve ser um email válido, por favor verifique a entrada e tente novamente!" at /var/www/vendor/sysborg/autentiquev2/src/utils.traits.php line 52`

```
 $token = $params['autentiqueToken'];

            $this->createFolder($params);

            $doc = new createDoc();
            $doc->name = 'Test with one signer';
            $doc->file = 'carta/carta_fornecedor.pdf';


            $signer = $doc->addSigners("um.email.valido@gmail.com");
            $signer->addPositions(20, 70, 1, 'SIGNATURE');
            $signer->addPositions(50, 20, 2, 'SIGNATURE');


            $aut = new autentique($doc);
            $aut->debug = true;
            $aut->token = $token;
            $result = $aut->transmit();

            echo '<br><br>//en-US: Response decoded | pt-BR: Resposta decodificada<br><pre>';
            var_dump(json_decode($result, true)); //en-US: Response decoded | pt-BR: Resposta decodificada
            echo '</pre><br><br>';
```

**Comment by FalaiTio** [comment]
Não sei ao certo, mas a validação de email (utils.traits.php) parece não funcionar

```
$exp = '/^([a-zA-Z0-9]{1,}[a-zA-Z0-9\\!\\#\\$\\%\\&\\*\\+\\-\\/\\=\\?\\^\\_\\`\\{\\|\\(\\)\\,\\:\\;\\<\\>\\@\\[\\\\\]]{1,}){1,65}\@[A-Za-z0-9\.\-]{1,}\.[a-z]{3}([a-z]{2,3})?$/';
            if(!preg_match($exp, $email))
                throw new \Exception('en-US: Variable '. $variableName. ' must be a valid email, please verify the entry and try again! | pt-BR: A variável '. $variableName. ' deve ser um email válido, por favor verifique a entrada e tente novamente!');
```

Entendi... essa validação não leva em consideração . ou - no email 
um.email.valido@gmail.com ou um-email-valido@gmail.com acusa erro

Algo que resolveria:
`$exp = '/^(?!(?:(?:\x22?\x5C[\x00-\x7E]\x22?)|(?:\x22?[^\x5C\x22]\x22?)){255,})(?!(?:(?:\x22?\x5C[\x00-\x7E]\x22?)|(?:\x22?[^\x5C\x22]\x22?)){65,}@)(?:(?:[\x21\x23-\x27\x2A\x2B\x2D\x2F-\x39\x3D\x3F\x5E-\x7E]+)|(?:\x22(?:[\x01-\x08\x0B\x0C\x0E-\x1F\x21\x23-\x5B\x5D-\x7F]|(?:\x5C[\x00-\x7F]))*\x22))(?:\.(?:(?:[\x21\x23-\x27\x2A\x2B\x2D\x2F-\x39\x3D\x3F\x5E-\x7E]+)|(?:\x22(?:[\x01-\x08\x0B\x0C\x0E-\x1F\x21\x23-\x5B\x5D-\x7F]|(?:\x5C[\x00-\x7F]))*\x22)))*@(?:(?:(?!.*[^.]{64,})(?:(?:(?:xn--)?[a-z0-9]+(?:-[a-z0-9]+)*\.){1,126}){1,}(?:(?:[a-z][a-z0-9]*)|(?:(?:xn--)[a-z0-9]+))(?:-[a-z0-9]+)*)|(?:\[(?:(?:IPv6:(?:(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){7})|(?:(?!(?:.*[a-f0-9][:\]]){7,})(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,5})?::(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,5})?)))|(?:(?:IPv6:(?:(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){5}:)|(?:(?!(?:.*[a-f0-9]:){5,})(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,3})?::(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,3}:)?)))?(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9]{2})|(?:[1-9]?[0-9]))(?:\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9]{2})|(?:[1-9]?[0-9]))){3}))\]))$/iD';`

esse regex de (https://emailregex.com/) leva em consideração email com . e com -
inclusive acusa erro se tiver 2 pontos ou ponto no inicio e fim do nome local
ex: um..email.invalido@gmail ou .um.email.invalido@gmail etc...

**Comment by sysborg** [comment]
Bom dia! Eu fiz alguns testes aparentemente funciona muito bem sua sugestão de expressão regular. Estarei substituindo a expressão regular pela sua sugestão. Agradeço desde já a contribuição!

**Comment by sysborg** [comment]
Fiz as correções necessárias agradeço novamente por compartilhar comigo essa sugestão que se mostrou bastante eficiente e foi pra versão do autentiquev2. Precisar estou sempre a disposição!
