### ISSUE TITLE
Inclusão de "sandbox" na query do layout createDoc

### ISSUE THREAD

**Issue by jm-borges** [sysborg/autentiquev2#3]
Olá, 

Utilizando a biblioteca, parece que mesmo havendo na classe autentique a possibilidade de setar o devMode, essa informação não é passada ao usar o layout createDoc, de forma que mesmo passando para a classe autentique true para devMode, ainda assim a query é enviada em modo produção.

Fiz algumas pequenas atualizações para uso em um projeto, e pensei em sugerir para incorporar na versão principal, caso seja de interesse.

Me avise que posso subir uma branch para analisarem ou enviar os pontos que foram atualizados.

Obrigado!

**Comment by andmarruda** [comment]
João, com certeza toda contribuição é sempre bem vinda, dessa forma podemos sempre melhorar e manter essa lib atualizada. Se puder criamos uma branch e vc poderá enviar la sim para avaliarmos um merge.

Novamente agradeço sua ajuda.

**Comment by sysborg** [comment]
Olá João boa noite! Como nosso principal colaborador Anderson disse, vai ser uma honra atualizar nosso código com suas melhorias, e se tiver sugestões sinta-se a vontade para compartilhar conosco. Criamos uma branch pra você poder nos enviar suas alterações, a branch chama homolog.

Novamente obrigado por nos ajudar e caso tenha opniões de melhorias por favor sinta-se a vontade para nos enviar.

**Comment by jm-borges** [comment]
Pessoal, boa noite.

Passei essas pequenas adições na branch no meu ambiente, mas não consegui subir o commit para a branch homolog por questão de não-autorização.
É possível que eu não possua permissão para passar commits para o repositório nessa branch?

Se puderem verificar, envio esse commit na sequência. 
Qualquer coisa me avisem que eu verifico se pode ser algum outro problema por aqui.

Obrigado!

**Comment by sysborg** [comment]
Salve João tudo bem? Te invitei como colaborador do projeto. Vai conseguir enviar push na branch homolog. Caso corra tudo bem e os códigos sejam aprovados eles serão integrados no main e um novo pacote será lançado.

Se puder também nos enviar um código exemplo pra poder ficar documentado como utilizar sua melhoria.

Agradeços muito seus empenhos. Qualquer coisa estamos a disposição.

**Comment by jm-borges** [comment]
Bom dia pessoal,

Obrigado, deu certo. Fiz a PR e expliquei as alterações e funcionamento lá.
Qualquer sugestão ou necessidade de alteração me avisem.

**Comment by sysborg** [comment]
@jm-borges obrigado pela ajuda, estaremos analisando e testando o funcionamento, assim que for analisado será aprovado e seus exemplos serão adicionados nas explicações! Quando isso acontecer eu avisarei você por aqui.

**Comment by sysborg** [comment]
@jm-borges eu e o Anderson vamos ter tempo no sábado ae já revisaremos e caso ocorra tudo bem já aprovamos sua alteração. Me diz tem mais algum ponto que acredita que poderia ser otimizado?

**Comment by andmarruda** [comment]
É com tremenda felicidade que podemos vir aqui e dizer que testamos e aprovamos suas mudanças.
Obrigado pela contribuição. Vou fechar essa issue mas sempre que tiver dúvidas ou quiser contribuir será muito bem vindo.

Forte abraço!

**Comment by jm-borges** [comment]
Bom dia pessoal.

Desculpem a demora em retornar, essa semana foi um tanto corrida.
Em termos de otimização, por agora não saberia dizer porque em um primeiro momento acabei usando o projeto mais para criação de documentos na Autentique mesmo, então não sei se as alterações que comentei se aplicariam às demais classes.
Mais pra frente, quando sobrar um tempinho, possivelmente precisarei usar as demais features, e ai já aproveito e vejo se teria algo a contribuir.

Agradeço por tudo, e fico à disposição também.

Grande abraço!
